/*
 * Copyright (c) 2000  Microsoft Corporation
 * Copyright (c) 2020 Oracle and/or its affiliates.
 */

//Spinlock macros
#define NPROT_INIT_LOCK(_pLock)           NdisAllocateSpinLock(_pLock)
#define NPROT_ACQUIRE_LOCK(_pLock, DispatchLevel)      \
    {                                                  \
        if (DispatchLevel == TRUE)                     \
        {                                              \
            NdisDprAcquireSpinLock(_pLock);            \
        }                                              \
        else                                           \
        {                                              \
            NdisAcquireSpinLock(_pLock);               \
        }                                              \
    }
#define NPROT_RELEASE_LOCK(_pLock, DispatchLevel)      \
    {                                                  \
        if (DispatchLevel == TRUE)                     \
        {                                              \
            NdisDprReleaseSpinLock(_pLock);            \
        }                                              \
        else                                           \
        {                                              \
            NdisReleaseSpinLock(_pLock);               \
        }                                              \
    }

#define NPROT_FREE_LOCK(_pLock)           NdisFreeSpinLock(_pLock)

//Cancel IDs are generated by using the partial cancel ID we got from
//NDIS ORed with a monotonically increasing locally generated ID.
#define NPROT_CANCEL_ID_LOW_MASK     (((ULONG_PTR)-1) >> 8)

#define NPROT_GET_NEXT_CANCEL_ID()                                                  \
        (PVOID)(Globals.PartialCancelId |                                           \
         ((NdisInterlockedIncrement((PLONG)&Globals.LocalCancelId)) & NPROT_CANCEL_ID_LOW_MASK))

//Events.
#define NPROT_INIT_EVENT(_pEvent)            NdisInitializeEvent(_pEvent)
#define NPROT_SIGNAL_EVENT(_pEvent)          NdisSetEvent(_pEvent)
#define NPROT_WAIT_EVENT(_pEvent, _MsToWait) NdisWaitEvent(_pEvent, _MsToWait)


//Flags
#define NPROT_SET_FLAGS(_FlagsVar, _Mask, _BitsToSet)    \
        (_FlagsVar) = ((_FlagsVar) & ~(_Mask)) | (_BitsToSet)

#define NPROT_TEST_FLAGS(_FlagsVar, _Mask, _BitsToCheck) \
        (((_FlagsVar) & (_Mask)) == (_BitsToCheck))
